# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-31 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('contributors_note', models.TextField(max_length=300)),
                ('website', models.URLField()),
                ('publisher', models.CharField(max_length=250)),
                ('content_type', models.CharField(max_length=100)),
                ('research_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('key_finding1', models.TextField(max_length=300)),
                ('key_finding2', models.TextField(max_length=300)),
                ('key_finding3', models.TextField(max_length=300)),
                ('comment', models.TextField()),
                ('content_rating_1', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_1_comment', models.TextField(max_length=300)),
                ('content_rating_2', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_2_comment', models.TextField(max_length=300)),
                ('content_rating_3', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_3_comment', models.TextField(max_length=300)),
                ('content_rating_4', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_4_comment', models.TextField(max_length=300)),
                ('content_rating_5', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_5_comment', models.TextField(max_length=300)),
                ('source_rating_1', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_1_comment', models.TextField(max_length=300)),
                ('source_rating_2', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_2_comment', models.TextField(max_length=300)),
                ('source_rating_3', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_3_comment', models.TextField(max_length=300)),
                ('source_rating_4', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_4_comment', models.TextField(max_length=300)),
                ('source_rating_5', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_5_comment', models.TextField(max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='category.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
