# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-05 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('key_finding1', models.TextField(max_length=300)),
                ('key_finding2', models.TextField(max_length=300)),
                ('key_finding3', models.TextField(max_length=300)),
                ('content_rating_1', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_1_comment', models.TextField(max_length=300)),
                ('content_rating_2', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_2_comment', models.TextField(max_length=300)),
                ('content_rating_3', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_3_comment', models.TextField(max_length=300)),
                ('content_rating_4', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_4_comment', models.TextField(max_length=300)),
                ('content_rating_5', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('content_rating_5_comment', models.TextField(max_length=300)),
                ('source_rating_1', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_1_comment', models.TextField(max_length=300)),
                ('source_rating_2', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_2_comment', models.TextField(max_length=300)),
                ('source_rating_3', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_3_comment', models.TextField(max_length=300)),
                ('source_rating_4', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_4_comment', models.TextField(max_length=300)),
                ('source_rating_5', models.CharField(choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1)),
                ('source_rating_5_comment', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_1',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_1_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_2',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_2_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_3',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_3_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_4',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_4_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_5',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='content_rating_5_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='key_finding1',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='key_finding2',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='key_finding3',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_1',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_1_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_2',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_2_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_3',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_3_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_4',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_4_comment',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_5',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='source_rating_5_comment',
        ),
        migrations.AddField(
            model_name='analysis',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='evidence.Evidence'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL),
        ),
    ]
