# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-05 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_auto_20180805_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='user',
            new_name='analyst',
        ),
    ]
