# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_auto_20180805_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='evidence.Evidence'),
        ),
    ]
