# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-07 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_auto_20180807_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='evidence',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='evidence.Evidence'),
            preserve_default=False,
        ),
    ]
