# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='This is Catg1'),
            preserve_default=False,
        ),
    ]
