# The content of this file was generated by IBM Cloud
# Do not modify it as it might get overridden

from ibmcloudenv import IBMCloudEnv
from . import service_manager
IBMCloudEnv.init()

from . import service_postgre
from . import service_weather_company_data


def initServices(app):
	
	name, service = service_postgre.getService()
	service_manager.set(name, service)

	name, service = service_weather_company_data.getService()
	service_manager.set(name, service)

	return
