# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-13 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0007_auto_20180812_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='publication_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='evidence',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='slug'),
            preserve_default=False,
        ),
    ]
